source:
  adapter: mysql
  encoding: utf8
  database: alertsmall
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

target:
  adapter: postgresql
  encoding: unicode
  database: alertsmall
  username: postgres
  password: typepassword

development:
  adapter: postgresql
  host: localhost
  pool: 5
  encoding: unicode
  database: alertsmall
  username: postgres
  password: typepassword


production:
  adapter: postgresql
  encoding: unicode
  database: alertsmall
  username: postgres
  password: 
