development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database:  alertsmall
  pool: 5
  username: root
  password: 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: alertsmall
  pool: 5
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: alertsmall 
  pool: 5
  username: root
  password: 
